{"name": "test_create_user", "status": "broken", "statusDetails": {"message": "TypeError: 'dict' object is not callable", "trace": "def test_create_user():\n        body = {\n        \"name\": \"morpheus\",\n        \"job\": \"leader\"\n        }\n        response = httpx.post(BASE_URL + CREATE_USER, json=body)\n        assert response.status_code == 201\n    \n        response_json = response.json()\n>       creation_date = response_json('createdAt')\nE       TypeError: 'dict' object is not callable\n\ntests\\test_work_user_data.py:20: TypeError"}, "start": 1738092945359, "stop": 1738092946052, "uuid": "386645be-83e3-49cc-a377-f33ddd8438e6", "historyId": "da73150bf80f71f27b0681aa1f2f9402", "testCaseId": "da73150bf80f71f27b0681aa1f2f9402", "fullName": "tests.test_work_user_data#test_create_user", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_work_user_data"}, {"name": "host", "value": "LAPTOP-LSAVBAAG"}, {"name": "thread", "value": "12224-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_work_user_data"}]}